
baseURL = "https://nuwaa.github.io/yueli-history/"
languageCode = "ja"
title = "ユエリーの台日近代史ノート"
theme = "LoveIt"
canonifyURLs = true
relativeURLs = false

[params]
  title = "ユエリーの台日近代史ノート"
  description = "台日近代史に関する調査記録"
  defaultTheme = "auto"
  showCodeCopyButtons = true
  dateFormat = "2006-01-02"
  showReadingTime = true
  showLastMod = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "ホーム"
    url = "/"
    weight = 1

[[menu.main]]
  identifier = "questions"
  name = "質問一覧"
  url = "/questions/"
  weight = 2

[outputs]
home = ["HTML", "RSS"]
section = ["HTML"]
