baseURL = "https://c1i.net/"
languageCode = "ja"
title = "ユエリーの台日近現代史ノート"
theme = "LoveIt"
canonifyURLs = true
relativeURLs = false
enableRobotsTXT = true
enableGitInfo   = true

[params]
  title = "ユエリーの台日近現代史ノート"
  description = "台湾と日本の歴史を優しく深く紹介するノート"
  images = ["/images/ogp-default.jpg"]
  defaultTheme = "auto"
  showCodeCopyButtons = true
  dateFormat = "2006-01-02"
  showReadingTime = true
  showLastMod = true
  enableHeadAddons = true

[params.assets]
  customCSS = ["css/custom.css"]

[[menu.main]]
  identifier = "home"
  name = "ホーム"
  url = "/"
  weight = 1

[[menu.main]]
  identifier = "questions"
  name = "質問一覧"
  url = "/questions/"
  weight = 2

[[menu.main]]
  name = "プライバシー"
  url = "/privacy-policy/"
  weight = 50

[[menu.main]]
  name = "お問い合わせ"
  url = "/contact/"
  weight = 60

[[menu.main]]
  name = "運営者情報"
  url = "/about/"
  weight = 70

  

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML"]

[params.footer]
copyright = "© 2025 月璃(Yueli)"

[params.author]
name = "月璃(Yueli)"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[taxonomies]
  category = "categories"
  tag = "tags"

[params.giscus]
  repo = "nuwaa/yueli-history"
  repo_id = "R_kgDOOaUmQA"
  category = "General"
  category_id = "DIC_kwDOOaUmQM4CqCve"
  mapping = "pathname"
  reactionsEnabled = "1"
  emitMetadata = "0"
  inputPosition = "bottom"
  theme = "preferred_color_scheme"
  lang = "ja"

