name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main  # ← main ブランチが更新されたら発火

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.125.3'
      - name: Clean public folder
        run: rm -rf public

      - name: Build
        run: hugo --minify

      - name: Create CNAME
        run: echo "c1i.net" > ./public/CNAME

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
